defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: stress_maps_development

test:
  <<: *defaults
  database: stress_maps_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: <%= ENV['MONGODB_URI'] %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
